apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamfactory
  namespace: dreamfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dreamfactory
  template:
    metadata:
      labels:
        app: dreamfactory
    spec:
      containers:
      - name: dreamfactory
        image: ${DF_IMAGE}
        ports:
        - containerPort: 80
        env:
        - name: DB_DRIVER
          value: sqlite
        - name: CACHE_DRIVER
          value: file
        - name: MYSQL_HOST
          value: ${MYSQL_HOST}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: REDIS_HOST
          value: ${REDIS_HOST}
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
