apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamfactory
  namespace: dreamfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dreamfactory
  template:
    metadata:
      labels:
        app: dreamfactory
    spec:
      containers:
      - name: dreamfactory
        image: dfregistry.azurecr.io/dreamfactory/df-docker:7.1.0
        ports:
        - containerPort: 80
        env:
        - name: DB_DRIVER
          value: sqlite
        - name: CACHE_DRIVER
          value: file
